### PR TITLE
Update to Erlang 18.0

### PR DESCRIPTION
**Pull request by eproxus**
This pull request does the following:
- Upgrades to the latest Erlang version, 18.0
- It also correctly tags the version in the repository as 18.0
- It uses the Erlang Solutions Debian repository package (earlier bug is fixed)
- Changes the base image to Ubuntu (Debian did not work with Elixir because of certificate issues)
- Updates the README (Erlang is not a database)

### CODE REVIEW

**Comment by gullitmiranda** [comment]
@eproxus, great contribution!

I've been testing [Alpine Linux](http://alpinelinux.org/) for a while and I believe it's even more interesting to use it instead of Debian.

I've created a personal repository in order to test it before migrating, what you think of using it?

Here's the Dockerfile:
https://github.com/gullitmiranda/docker-elixir/blob/master/1.0.5/Dockerfile

We can also improve it and separate the Erlang's installation (https://github.com/azukiapp/docker-erlang/pull/2).

**Comment by eproxus** [comment]
Yes, I was also thinking about that.

The conclusion I came to was that it's maybe better for actual deployment via Docker (of which Erlang apps are less suited). Since I'm currently working on getting a reproducible development environment going for my team, I thought it would be useful with a full and familiar Ubuntu environment.

I still haven't figured out the best way to interact with the Docker images, if `azk shell` is done first and then all development in there, or if the container is just used to run the system. The problem we have, is that we're developing on OS X so compiling code there (with native libraries) doesn't work since it won't run under Linux then.

**Comment by eproxus** [comment]
Also, some Erlang libraries (like [`erlexec`](https://github.com/saleyn/erlexec) and I assume some other Linux tools) doesn't like being run as `root`. I haven't found a really nice way to work around this (see https://github.com/azukiapp/azk/issues/517).

**Comment by gullitmiranda** [comment]
I see your point. I think it's pretty much the same difference (with respect to usability) using the debian or alpine.

We have a project in Elixir using azk in development environment and staging, and has worked very well. Other users are in the same scenario.

Regarding the issue https://github.com/azukiapp/azk/issues/517, we did some tests based on the way we recommend. To facilitate and also document will post a comment with an example. This way is good for you?

**Comment by eproxus** [comment]
Yeah, having that documented would be nice. :-) I managed to get something to run at least (doesn't work yet).

Have you guys done anything with private dependencies with Erlang or Elixir? I'm currently having trouble running `mix deps.get` with private repositories as dependencies. My GitHub auth and keys are not in the Docker instance, obviously.

**Comment by gullitmiranda** [comment]
We do not have private dependencies, but I do a `mount` of my http://hex.pm credentials to publish some packages that I maintain.

**Comment by eproxus** [comment]
Yeah, figured out that mounting my `~/.ssh` does the trick for now.

**Comment by gullitmiranda** [comment]
nice.

**Comment by gullitmiranda** [comment]
image update using alpine

**Pull request closed without merging**
